# ENCIG: 2023

In [1]:
import pandas as pd
import plotly.express as px

### P3_3_01: Percepción de frecuencia de corrupción en las universidades públicas

In [2]:
df = pd.read_csv('./data/encig2023_01_sec1_A_3_4_5_8_9_10.csv', index_col=0)

In [3]:
df.head()

,ID_PER,ID_VIV,CVE_ENT,NOM_ENT,CVE_MUN,NOM_MUN,AREAM,NOM_AREAM,UPM,PRO_VIV,...,P10_1_2,P10_1_3,P10_1_4,P10_1_5,P10_1_6,EST_DIS,UPM_DIS,EST,FAC_VIV,FAC_P18
1,09.0900342.01.01,09.0900342.01,9,CIUDAD DE MEXICO,2,AZCAPOTZALCO,1,CIUDAD DE MEXICO,900342,124,...,2,1,2,1,2,85,2146,3,659,1317
2,09.0900335.03.03,09.0900335.03,9,CIUDAD DE MEXICO,2,AZCAPOTZALCO,1,CIUDAD DE MEXICO,900335,55,...,2,2,2,2,2,85,2145,3,559,1678
3,09.0900335.04.01,09.0900335.04,9,CIUDAD DE MEXICO,2,AZCAPOTZALCO,1,CIUDAD DE MEXICO,900335,73,...,1,1,2,2,2,85,2145,3,559,1678
5,09.0900342.05.01,09.0900342.05,9,CIUDAD DE MEXICO,2,AZCAPOTZALCO,1,CIUDAD DE MEXICO,900342,16,...,2,2,2,2,2,85,2146,3,659,659
6,09.0900342.02.02,09.0900342.02,9,CIUDAD DE MEXICO,2,AZCAPOTZALCO,1,CIUDAD DE MEXICO,900342,142,...,2,1,2,1,2,85,2146,3,659,1317

In [4]:
# P3_3_01 -> Percepción de corrupción en instituciones educativas (Target)
# P5_3A -> Satisfacción con la educación pública superior recibida (Target)

# P5_3_1 -> Educacion publica superior: Instalaciones y mobiliario
# P5_3_2 -> Educacion publica superior: Instalaciones limpias y ordenadas
# P5_3_3 -> Educacion publica superior: Cumplimiento de temarios
# P5_3_4 -> Educacion publica superior: Cumplimiendo de dias de clase programados
# P5_3_5 -> Educacion publica superior: Personal docente suficiente
# P5_3_6 -> Educacion publica superior: Personal docente capacida
# P5_3_7 -> Educacion publica superior: Salones sin saturacion de estudiantes
# P5_3_8 -> Educacion publica superior: Calidad de enseñanza que garantiza acceso a siguiente nivel o buen trabajo

In [5]:
ndf = df.copy()
ndf = ndf.loc[ndf['P5_1_02'] == 1] # Solo estudiantes activos en 2023

ndf.loc[ndf['P3_3_01'] == 9, 'P3_3_01'] = pd.NA # Convertir "No sabe/no responde" a NA
ndf.loc[ndf['P5_3A'] == 9, 'P5_3A'] = pd.NA # Convertir "No sabe/no responde" a NA

ndf.loc[ndf['P5_3_1'] == 9, 'P5_3_1'] = pd.NA # Convertir "No sabe/no responde" a NA
ndf.loc[ndf['P5_3_2'] == 9, 'P5_3_2'] = pd.NA # Convertir "No sabe/no responde" a NA
ndf.loc[ndf['P5_3_3'] == 9, 'P5_3_3'] = pd.NA # Convertir "No sabe/no responde" a NA
ndf.loc[ndf['P5_3_4'] == 9, 'P5_3_4'] = pd.NA # Convertir "No sabe/no responde" a NA
ndf.loc[ndf['P5_3_5'] == 9, 'P5_3_5'] = pd.NA # Convertir "No sabe/no responde" a NA
ndf.loc[ndf['P5_3_6'] == 9, 'P5_3_6'] = pd.NA # Convertir "No sabe/no responde" a NA
ndf.loc[ndf['P5_3_7'] == 9, 'P5_3_7'] = pd.NA # Convertir "No sabe/no responde" a NA
ndf.loc[ndf['P5_3_8'] == 9, 'P5_3_8'] = pd.NA # Convertir "No sabe/no responde" a NA

ndf.dropna(subset=['P3_3_01',
                  'P5_3_1',
                  'P5_3_2',
                  'P5_3_3',
                  'P5_3_4',
                  'P5_3_5',
                  'P5_3_6',
                  'P5_3_7',
                  'P5_3_8',
                  'P5_3A'], inplace=True)

ndf.reset_index(drop=True, inplace=True)

In [6]:
ndf

,ID_PER,ID_VIV,CVE_ENT,NOM_ENT,CVE_MUN,NOM_MUN,AREAM,NOM_AREAM,UPM,PRO_VIV,...,P10_1_2,P10_1_3,P10_1_4,P10_1_5,P10_1_6,EST_DIS,UPM_DIS,EST,FAC_VIV,FAC_P18
0,09.0900342.01.01,09.0900342.01,9,CIUDAD DE MEXICO,2,AZCAPOTZALCO,1,CIUDAD DE MEXICO,900342,124,...,2,1,2,1,2,85,2146,3,659,1317
1,09.0900010.04.03,09.0900010.04,9,CIUDAD DE MEXICO,2,AZCAPOTZALCO,1,CIUDAD DE MEXICO,900010,90,...,1,2,2,1,2,85,2123,3,650,1951
2,09.0900120.03.03,09.0900120.03,9,CIUDAD DE MEXICO,2,AZCAPOTZALCO,1,CIUDAD DE MEXICO,900120,80,...,1,2,2,2,2,85,2126,3,485,1454
3,09.0900219.01.04,09.0900219.01,9,CIUDAD DE MEXICO,2,AZCAPOTZALCO,1,CIUDAD DE MEXICO,900219,62,...,1,2,2,1,2,85,2134,3,877,4383
4,09.0900291.03.02,09.0900291.03,9,CIUDAD DE MEXICO,2,AZCAPOTZALCO,1,CIUDAD DE MEXICO,900291,79,...,2,1,2,1,2,85,2141,3,585,1170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2543,20.2000868.03.04,20.2000868.03,20,OAXACA,184,SAN JUAN BAUTISTA TUXTEPEC,0,RESTO DE CIUDADES DE 100 MIL HABITANTES Y MAS,2000868,66,...,2,2,2,2,2,206,5908,2,279,1393
2544,20.2000872.04.03,20.2000872.04,20,OAXACA,184,SAN JUAN BAUTISTA TUXTEPEC,0,RESTO DE CIUDADES DE 100 MIL HABITANTES Y MAS,2000872,136,...,1,1,2,2,2,206,5909,2,352,1055
2545,20.2000897.04.01,20.2000897.04,20,OAXACA,184,SAN JUAN BAUTISTA TUXTEPEC,0,RESTO DE CIUDADES DE 100 MIL HABITANTES Y MAS,2000897,119,...,2,2,2,2,2,206,5911,2,244,244
2546,20.2000914.03.02,20.2000914.03,20,OAXACA,184,SAN JUAN BAUTISTA TUXTEPEC,0,RESTO DE CIUDADES DE 100 MIL HABITANTES Y MAS,2000914,135,...,1,2,2,2,2,206,5915,2,310,620
2547,20.2000819.05.03,20.2000819.05,20,OAXACA,184,SAN JUAN BAUTISTA TUXTEPEC,0,RESTO DE CIUDADES DE 100 MIL HABITANTES Y MAS,2000819,1,...,1,2,1,2,2,206,5898,2,217,652

In [16]:
# Plot de pie chart sobre perceción de corrupción

dict_per = {
    1: 'Muy frecuente',
    2: 'Frecuente',
    3: 'Poco frecuente',
    4: 'Nunca'
}

fig = px.pie(ndf['P3_3_01'].map(dict_per), names='P3_3_01', title='Percepción de corrupción entre estudiantes activos en 2023')
fig.show()

In [17]:
# Plot de pie chart sobre perceción de corrupción

dict_sats = {
    1: 'Muy satisfecho',
    2: 'Satisfecho',
    3: 'Poco satisfecho',
    4: 'Nada satisfecho'
}

fig = px.pie(ndf['P5_3A'].map(dict_sats), names='P5_3A', title='Satisfacción con la educación pública superior recibida entre estudiantes activos en 2023')
fig.show()

In [33]:
# Heatmap de correlación entre variables
import plotly.figure_factory as ff

corr_matrix = ndf[['P3_3_01',
                    'P5_3A',
                   'P5_3_1',
                   'P5_3_2',
                   'P5_3_3',
                   'P5_3_4',
                   'P5_3_5',
                   'P5_3_6',
                   'P5_3_7',
                   'P5_3_8']].corr()

# Truncate corr_matrix to 2 decimal places
corr_matrix = corr_matrix.round(2)

col_dict = {
    'P3_3_01': 'Percepción de corrupción',
    'P5_3A': 'Satisfacción con la educación pública superior recibida',
    'P5_3_1': 'Instalaciones y mobiliario',
    'P5_3_2': 'Instalaciones limpias y ordenadas',
    'P5_3_3': 'Cumplimiento de temarios',
    'P5_3_4': 'Cumplimiendo de dias de clase programados',
    'P5_3_5': 'Personal docente suficiente',
    'P5_3_6': 'Personal docente capacida',
    'P5_3_7': 'Salones sin saturacion de estudiantes',
    'P5_3_8': 'Calidad de enseñanza que garantiza acceso a siguiente nivel o buen trabajo'
}

fig = ff.create_annotated_heatmap(
    z=corr_matrix.values,
    x=[col_dict[col] for col in corr_matrix.columns],
    y=[col_dict[row] for row in corr_matrix.index],
    colorscale='Viridis',
    showscale=True,
    annotation_text=corr_matrix.values.astype(str)
)

fig.update_xaxes(tickangle=90)
# Change text size of X and Y axis
fig.update_xaxes(tickfont=dict(size=5))
fig.update_yaxes(tickfont=dict(size=5))

fig.update_layout(title_text='Matriz de correlación entre variables')
fig.show()

In [35]:
# Seleccion de características basada en correlación

mcorp3 = corr_matrix['P3_3_01'].abs().sort_values(ascending=False)

# Remove 'Percepción de corrupción' from mcorp3
mcorp3 = mcorp3.drop('P3_3_01')

# Plot mcorp3 as bar chart
# Use dict col_dict to rename x axis labels without modifying mcorp3 index
fig = px.bar(mcorp3, x=[col_dict[col] for col in mcorp3.index], y=mcorp3.values,
             labels={'x': 'Variables', 'y': 'Correlación absoluta con Percepción de corrupción'},
             title='Correlación de variables con Percepción de corrupción')
fig.show()

Mejor hay que preguntarnos entonces que hace que la gente este más satisfecha o insatisfecha con la educación pública superior que recibe.

In [36]:
# Seleccion de características basada en correlación

mcorp5 = corr_matrix['P5_3A'].abs().sort_values(ascending=False)
# Remove 'Satisfacción con la educación pública superior recibida' from mcorp5
mcorp5 = mcorp5.drop('P5_3A')
# Plot mcorp5 as bar chart
# Use dict col_dict to rename x axis labels without modifying mcorp5 index
fig = px.bar(mcorp5, x=[col_dict[col] for col in mcorp5.index], y=mcorp5.values,
             labels={'x': 'Variables', 'y': 'Correlación absoluta con Satisfacción con la educación pública superior recibida'},
             title='Correlación de variables con Satisfacción con la educación pública superior recibida')
fig.show()

In [40]:
mcorp5

P5_3_8     0.54
P5_3_1     0.44
P5_3_3     0.44
P5_3_2     0.39
P5_3_6     0.39
P5_3_5     0.38
P5_3_4     0.32
P5_3_7     0.27
P3_3_01    0.23
Name: P5_3A, dtype: float64

In [41]:
# Cálculo del p-valor para la correlación entre P5_3A y P5_3_8
from scipy.stats import pearsonr

corr, pval = pearsonr(ndf['P5_3A'], ndf['P5_3_8'])
print(f"Correlación: {corr:.3f}, p-valor: {pval:.4f}")

Correlación: 0.536, p-valor: 0.0000